create database db_email;

create table emails (
	id serial primary key,
	email varchar(255) not null,
	has_sent boolean default false,
	created_at timestamp default current_timestamp,
	updated_at timestamp default current_timestamp
);

INSERT INTO emails (email, has_sent, created_at, updated_at) VALUES 
('shenna.w@archipelagohotels.com', false, now(), now()),
('indriawigati@gmail.com', false, now(), now()),
('deisy153lake@gmail.com', false, now(), now()),
('cv.17makmur@gmail.com', false, now(), now()),
('4bersaudara.trk@gmail.com', false, now(), now()),
('cv88solutions@gmail.com', false, now(), now()),
('cikancung667768@gmail.com', false, now(), now()),
('aaproject99@gmail.com', false, now(), now()),
('cv.aabid@gmail.com', false, now(), now()),
('cv.abadijaya.kutim@gmail.com', false, now(), now()),
('abadigranitprima@gmail.com', false, now(), now()),
('cvabadimakmurpati@yahoo.co.id', false, now(), now()),
('usmansondatayang@gmail.com', false, now(), now()),
('abbiyubangun@gmail.com', false, now(), now()),
('abadigranitprima@gmail.com', false, now(), now()),
('aceenc@ymail.com', false, now(), now()),
('ptaciabadi@gmail.com', false, now(), now()),
('busdevapi@acset.co', false, now(), now()),
('adamas_globalindo@yahoo.com', false, now(), now()),
('adcocitraasri@hotmail.com', false, now(), now()),
('adhinet@adhi.co.id', false, now(), now()),
('adhimixpci2@gmail.com', false, now(), now()),
('adibuana_sp@yahoo.co.id', false, now(), now()),
('akh_adicipta@yahoo.com', false, now(), now()),
('adimaskantata99@gmail.com', false, now(), now()),
('ptadinataindustriraja@gmail.com', false, now(), now()),
('adinata.pembangun@outlook.com', false, now(), now()),
('malvinnugrahaa@gmail.com', false, now(), now()),
('adipranaindovesco@gmail.com', false, now(), now()),
('adi.suryadinata.23@gmail.com', false, now(), now()),
('adiwastramakmursejahtera@gmail.com', false, now(), now()),
('yansen.alfrits@ambpi.com', false, now(), now()),
('adonia_tritunggal_pt@yahoo.com', false, now(), now()),
('afhamsolusikomunikasi@gmail.com', false, now(), now()),
('agregate_citrapersada@yahoo.com', false, now(), now()),
('agungsedayupermai@worldmailserver.com', false, now(), now()),
('alamhasilmulia@gmail.com', false, now(), now()),
('steven.biohome@gmail.com', false, now(), now()),
('alcosgrahajaya@gmail.com', false, now(), now()),
('alfacitrakaryatama.pt@gmail.com', false, now(), now()),
('algypgraha@gmail.com', false, now(), now()),
('alifsamudrajaya0920@gmail.com', false, now(), now()),
('alita@alita.id', false, now(), now()),
('alkoputra2021@gmail.com', false, now(), now()),
('alkosaudara21@gmail.com', false, now(), now()),
('ptallanddiarrapratama@gmail.com', false, now(), now()),
('allisa.konstruksi@gmail.com', false, now(), now()),
('mustadi@almajara.co.id', false, now(), now()),
('pt.arn@gmail.comm', false, now(), now()),
('alphabangunindonesia3@gmail.com', false, now(), now()),
('contact@alphaomeganusantara.com', false, now(), now()),
('alpinecool@frigostar.net', false, now(), now()),
('altekmessiatoluj@yahoo.com', false, now(), now()),
('altrivamurilestari@gmail.com', false, now(), now()),
('pt.amantarakalyana@gmail.com', false, now(), now()),
('amarta.lestarikn@gmail.com', false, now(), now()),
('ferryanto.amavi@gmail.com', false, now(), now()),
('ptamertarajawalikonstruksi@gmail.com', false, now(), now()),
('anandarchelianpratama@gmail.com', false, now(), now()),
('inquiiries@andalanmining.co.id', false, now(), now()),
('andalanmitra.b@gmail.com', false, now(), now());




